### ISSUE TITLE
Support for Teensy 3.2

### ISSUE THREAD

**Issue by harshit-aggarwal** [marcmerlin/AnimatedGIFs#1]
Do you support playing gifs through a Teensy 3.2 without a SD card? I was looking through the config file and only found the Teensy 3.5/6.

Great library anyway!

**Comment by marcmerlin** [comment]
teensy is supported in the original library (which I didn't write), but how do you plan on using this without an sdcard?
If you don't want an sdcard, you have to use an ESP8266 with FastLED::NeoMatrix, or an ESP32 with Fastled::NeoMatrix or SmartMatrix (those two chips support SPIFFS or FatFS, while teensy does not AFAIK)
