### ISSUE TITLE
[Goodies: new animated gifs]

### ISSUE THREAD

**Issue by GraspGG** [marcmerlin/AnimatedGIFs#16]
If you don't mind, i would add the one or the other self made animated gif 64 x 64 px over time using this "issue", starting with these two...

![FloppyFlash](https://github.com/marcmerlin/AnimatedGIFs/assets/6455912/8946606b-0bac-4f9e-abc7-106b581afdcf)
5 1/4" Floppy Disk > morphing into 3 1/2" Floppy Disk > morphing into SD Card

![BatterieG](https://github.com/marcmerlin/AnimatedGIFs/assets/6455912/71786563-4e2d-4f6a-8919-aa2c1ca8a213)
Empty Battery > Power Sign > Battery 25% green > Battery 50% green > 75% > 100 % > Power Sign disappears

...as kind of "THANK YOU" for this repo, which saved me some hours lifetime 💯

Merry Christmas everyone!

P.S. If there is acertain place to "drop" new or additional gifs, please let me know

=====================
EDIT reason: New gifs

![Network-wireless](https://github.com/marcmerlin/AnimatedGIFs/assets/6455912/cef7d00b-4992-45b0-a44b-e3ff3f7c220c)
Wireless Network Signal strength: 100% > 75% > 50% > 25% > 0% >>>

![weather-day](https://github.com/marcmerlin/AnimatedGIFs/assets/6455912/fed445e6-a8d5-4cc7-afdd-81022a5a0b26)
Weather Indicators Day:
• with Sun - Clear > few Clouds > Clouds > scattered Showers > Showers > Snow > Storm
• no Sun - Mist > Many Clouds > Snow Rain > Hail > Severe Alert

![weather-night](https://github.com/marcmerlin/AnimatedGIFs/assets/6455912/08043d2d-b542-4f1a-a79c-fbe229364bfe)
Weather Indicators Night:
• with Moon - Clear > few Clouds > Clouds > scattered Showers > Showers > Snow > Storm
• no Moon - Mist > Many Clouds > Snow Rain > Hail > Severe Alert

**Comment by marcmerlin** [comment]
I added a few to the main branch, thanks
