### ISSUE TITLE
Off-by-one error in getGIFFilenameByIndex

### ISSUE THREAD

**Issue by rorosaurus** [marcmerlin/AnimatedGIFs#3]
This error is why the last alphabetically gif is always index 0, then after that the filename indexes descend as expected.

I'm not sure if this affects the other targets, but I'll put out a quick PR for ESP32.

**Comment by marcmerlin** [comment]
thanks Rory.
I'm on a dive boat, so I can't easily look at this right now, but definitely will, and it seems your fix should work.

**Comment by rorosaurus** [comment]
No rush! Be safe and enjoy, Marc!

**Comment by marcmerlin** [comment]
oops, I fixed this, but never closed it, sorry
