### ISSUE TITLE
esp32 smartmatrix wiring + sdcard

### ISSUE THREAD

**Issue by harissutanrafiq** [marcmerlin/AnimatedGIFs#6]
can you show to me, how to wiring ledmatrix using esp32 + sdcard ..?

**Comment by marcmerlin** [comment]
Sorry, I can't provide 1-1 help with project building/wiring
See
- http://marc.merlins.org/perso/arduino/post_2019-04-01_SmartMatrix_-SmartMatrix-Shield-v4-for-Teensy_-ESP32-shield-with-level-shifter_-and-SmartMatrix_GFX.html#ESP32
- https://github.com/pixelmatix/SmartMatrix/blob/teensylc/src/MatrixHardware_ESP32_V0.h#L62

For sdcard, I can't help, I use SPIFFS on ESP32, so you'll have to try that one on your own. 

Before you worry animated gifs, get RGBPanels working first, see https://community.pixelmatix.com/ if you need help with that.
If you post, please say what you tried and what didn't work before you proceed.
